### DISCUSSION TITLE
Translating Detectron1 config file to Detectron2?

### DISCUSSION THREAD

**Discussion by cooldecola** [facebookresearch/detectron2#3478] [Q&A]
Hey guys, I have a yaml file in detectron that I used to train a model. I am now trying to convert to detectron2 and can't seem to find the same parameters in detectron2. 

This is the yaml file in detectron: 
```
MODEL: 
  TYPE: generalized-rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  FASTER_RCNN: True

NUM_GPUS: 1

SOLVER: 
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 5400
  STEPS: [0, 3000, 4000]

FPN: 
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True

FAST_RCNN: 
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2

TRAIN: 
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('d1', )
  SCALES: (500,)
  MAX_SIZE: 833
  BATCH_SIZE_PER_IM: 256
  RPN_PRE_NMS_TOP_N: 2000
```
D1 = detectron1
D2 = detectron2 

### Problem 1
In D1 I set `CONV_BODY: FPN.add_fpn_ResNet50_conv5_body` however in D2 I have it set as `cfg.merge_from_file(model_zoo.get_config_file("Base-RCNN-FPN.yaml"))`. Inside Base-RCNN-FPN.yaml I see
```
BACKBONE:
    NAME: "build_resnet_fpn_backbone"
```

Are these backbones the same? `build_resnet_fpn_backbone` does not specify if it is ResNet50

### Problem 2
How do I set how many GPU's  ? In D1 I have `NUM_GPUS: 1` but nothing similar in D2? 

### Problem 3
Under the FPN section of my yaml config file I have set
```
FPN: 
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
```
I don't have the option to use FPN for RoI transforms or using FPN for RPN. Is there a way to do this? 

### Problem 4
Same issue with the `FAST_RCNN ` options. I cannot find similar options that translate over. 

The following is what I have implemented so far in D2 but I'm not sure if this is correct: 

```
cfg.MODEL.ROI_BOX_HEAD.NAME = "FastRCNNConvFCHead"
cfg.MODEL.ROI_BOX_HEAD.BBOX_REG_LOSS_TYPE = "smooth_li"
cfg.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7
cfg.MODEL.ROI_BOX_HEAD.POOLER_SAMPLER_RATIO = 2
```

### Last Problem
I have set `BATCH_SIZE_PER_IM = 256 ` in D1. 
Is this the same as c`fg.MODEL.BATCH_SIZE_PER_IMAGE = 256` ? 
The reason I am asking is that in D1 the BATCH_SIZE_PER_IM falls under the training category, however in D2 it's under the model category. I think they should be the same but I just wanted to clarify. 

Any help would be greatly appreciated, thanks in advance! :)
