### DISCUSSION TITLE
How to understand the maskRCNN config about the max_iter ?

### DISCUSSION THREAD

**Discussion by HuangChiEn** [facebookresearch/detectron2#4624] [Q&A]
it's hard to understand the [config](https://github.com/facebookresearch/detectron2/blob/main/configs/Base-RCNN-C4.yaml) of maskrcnn :

```
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
```
Since, coco_2017_train have 118000 images in used during training, then how could this config valid ?
`epoch = MAX_ITER *  IMS_PER_BATCH / 118000`
i try to figure out how many epoch will it run, but this equation seems can not be solved. It seems only run 12 epoch.

Any suggestion will be appreciated !!
