### ISSUE TITLE
Infinite losses with CROP.ENABLED = True

### ISSUE THREAD

**Issue by cbasavaraj** [facebookresearch/detectron2#1102]
Hi, I'm using Faster RCNN with FPN for instance detection on a custom dataset. Training worked fine with `faster_rcnn_R_101_FPN_3x.yaml`. In order to try and improve results, I am trying various things. I tried rotations, got it to work, but the results are not better. Now trying random crops. 

Training is crashing unpredictably due to losses becoming infinite. I think my dataset is fine as I used exactly the same images + annotations in Coco JSON format for my baseline model. The crop transform is also working fine as far as I can tell, looking at the results of `visualize_data.py`.

The error happens not at the beginning of training, but after a few hundred, or a few thousand iterations, as the losses start diverging: 

```
File "/home/dev_cloud/ka/detectron2/projects/AIR/plain_train_net.py", line 209, in do_train
    assert torch.isfinite(losses).all(), loss_dict
AssertionError: {'loss_cls': tensor(nan, device='cuda:0', grad_fn=<NllLossBackward>), 'loss_box_reg': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>), 'loss_rpn_cls': tensor(0.7206, device='cuda:0', grad_fn=<MulBackward0>), 'loss_rpn_loc': tensor(0.0663, device='cuda:0', grad_fn=<MulBackward0>)}
```

My config file is as below:
```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
INPUT:
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.70, 0.70]
```

I'm now going to try:
```
SOLVER:
  CLIP_GRADIENTS: True
```

Need to wait and see if I get infinite losses again. Could be a few thousand iterations before this happens though. In the meanwhile, if anyone else has faced this problem or has a solution, would be happy to hear!
