### ISSUE TITLE
Object Detection with Faster R-CNN Evaluation Error

### ISSUE THREAD

**Issue by YavuzSelimGugen** [facebookresearch/detectron2#1502]
I'm trying to train a faster r-cnn on mmfashion dataset. I load my dataset as COCO and trained without any error. But when i tried to evaluate i got errors like, KeyError: 'area', KeyError: 'iscrowd'. These keys for segmentation and i'm doing only detection so my json file doesn't include them.
 
[full code](https://colab.research.google.com/drive/1rcN2LTh-8FjdJxDc_v6ZoTQYKaqQTQt-)

structure of my jsons:

 ```
 "images": [
    {
      "id": `0,`
      "file_name": "xx.jpg",
      "width": 300,
      "height": 300
    }
 ],
"annotations": [
    {
      "bbox": [x,y,h,w],
      "id": 0,
      "image_id": 0,
      "category_id": 0
    }"
]
...
```

Here is the code that train and evaluate part:

```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = (mmfashion_instance_train,)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml")
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 50

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```
Output:

```
[05/30 17:32:57 d2.data.datasets.coco]: Loaded 20 images in COCO format from ./trainS.json
[05/30 17:32:57 d2.data.build]: Removed 0 images with no usable annotations. 20 images left.
[05/30 17:32:57 d2.data.common]: Serializing 20 elements to byte tensors and concatenating them all ...
[05/30 17:32:57 d2.data.common]: Serialized dataset takes 0.00 MiB
[05/30 17:32:57 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[05/30 17:32:57 d2.data.build]: Using training sampler TrainingSampler

'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (51, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (51,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (200, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (200,) in the model! Skipped.

[05/30 17:32:58 d2.engine.train_loop]: Starting training from iteration 0
[05/30 17:33:05 d2.utils.events]:  eta: 0:01:44  iter: 19  total_loss: 4.396  loss_cls: 3.906  loss_box_reg: 0.472  loss_rpn_cls: 0.001  loss_rpn_loc: 0.008  time: 0.3686  data_time: 0.0162  lr: 0.000005  max_mem: 5158M
[05/30 17:33:13 d2.utils.events]:  eta: 0:01:37  iter: 39  total_loss: 4.169  loss_cls: 3.711  loss_box_reg: 0.427  loss_rpn_cls: 0.002  loss_rpn_loc: 0.009  time: 0.3758  data_time: 0.0054  lr: 0.000010  max_mem: 5227M
[05/30 17:33:20 d2.utils.events]:  eta: 0:01:31  iter: 59  total_loss: 3.806  loss_cls: 3.266  loss_box_reg: 0.436  loss_rpn_cls: 0.001  loss_rpn_loc: 0.011  time: 0.3787  data_time: 0.0047  lr: 0.000015  max_mem: 5227M
[05/30 17:33:27 d2.utils.events]:  eta: 0:01:21  iter: 79  total_loss: 3.069  loss_cls: 2.507  loss_box_reg: 0.517  loss_rpn_cls: 0.001  loss_rpn_loc: 0.011  time: 0.3695  data_time: 0.0047  lr: 0.000020  max_mem: 5227M
[05/30 17:33:34 d2.utils.events]:  eta: 0:01:13  iter: 99  total_loss: 1.839  loss_cls: 1.376  loss_box_reg: 0.488  loss_rpn_cls: 0.001  loss_rpn_loc: 0.009  time: 0.3665  data_time: 0.0049  lr: 0.000025  max_mem: 5227M
[05/30 17:33:42 d2.utils.events]:  eta: 0:01:06  iter: 119  total_loss: 1.375  loss_cls: 0.789  loss_box_reg: 0.551  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3659  data_time: 0.0050  lr: 0.000030  max_mem: 5227M
[05/30 17:33:49 d2.utils.events]:  eta: 0:00:57  iter: 139  total_loss: 1.052  loss_cls: 0.570  loss_box_reg: 0.505  loss_rpn_cls: 0.001  loss_rpn_loc: 0.012  time: 0.3653  data_time: 0.0047  lr: 0.000035  max_mem: 5227M
[05/30 17:33:56 d2.utils.events]:  eta: 0:00:51  iter: 159  total_loss: 0.994  loss_cls: 0.496  loss_box_reg: 0.480  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3654  data_time: 0.0052  lr: 0.000040  max_mem: 5227M
[05/30 17:34:04 d2.utils.events]:  eta: 0:00:44  iter: 179  total_loss: 0.982  loss_cls: 0.437  loss_box_reg: 0.521  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3655  data_time: 0.0043  lr: 0.000045  max_mem: 5227M
[05/30 17:34:11 d2.utils.events]:  eta: 0:00:36  iter: 199  total_loss: 0.851  loss_cls: 0.357  loss_box_reg: 0.475  loss_rpn_cls: 0.001  loss_rpn_loc: 0.013  time: 0.3656  data_time: 0.0048  lr: 0.000050  max_mem: 5227M
[05/30 17:34:19 d2.utils.events]:  eta: 0:00:29  iter: 219  total_loss: 0.797  loss_cls: 0.269  loss_box_reg: 0.521  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3669  data_time: 0.0047  lr: 0.000055  max_mem: 5227M
[05/30 17:34:26 d2.utils.events]:  eta: 0:00:22  iter: 239  total_loss: 0.777  loss_cls: 0.205  loss_box_reg: 0.553  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3661  data_time: 0.0055  lr: 0.000060  max_mem: 5227M
[05/30 17:34:33 d2.utils.events]:  eta: 0:00:14  iter: 259  total_loss: 0.734  loss_cls: 0.163  loss_box_reg: 0.553  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3656  data_time: 0.0047  lr: 0.000065  max_mem: 5227M
[05/30 17:34:40 d2.utils.events]:  eta: 0:00:07  iter: 279  total_loss: 0.759  loss_cls: 0.147  loss_box_reg: 0.607  loss_rpn_cls: 0.001  loss_rpn_loc: 0.010  time: 0.3649  data_time: 0.0045  lr: 0.000070  max_mem: 5227M
[05/30 17:34:49 d2.utils.events]:  eta: 0:00:00  iter: 299  total_loss: 0.729  loss_cls: 0.127  loss_box_reg: 0.584  loss_rpn_cls: 0.000  loss_rpn_loc: 0.008  time: 0.3649  data_time: 0.0046  lr: 0.000075  max_mem: 5227M
[05/30 17:34:50 d2.engine.hooks]: Overall training speed: 297 iterations in 0:01:48 (0.3661 s / it)
[05/30 17:34:50 d2.engine.hooks]: Total training time: 0:01:51 (0:00:02 on hooks)

```

```
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.DATASETS.TEST = (mmfashion_instance_test, )
predictor = DefaultPredictor(cfg)
```

Evaluate part:

```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset, RotatedCOCOEvaluator
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator(mmfashion_instance_test, cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, mmfashion_instance_test)
inference_on_dataset(trainer.model, val_loader, evaluator)
# another equivalent way is to use trainer.test
```

output:

```
[05/30 17:38:22 d2.data.datasets.coco]: Loaded 20 images in COCO format from ./testS.json
[05/30 17:38:22 d2.data.common]: Serializing 20 elements to byte tensors and concatenating them all ...
[05/30 17:38:22 d2.data.common]: Serialized dataset takes 0.00 MiB
[05/30 17:38:22 d2.evaluation.evaluator]: Start inference on 20 images
[05/30 17:38:23 d2.evaluation.evaluator]: Inference done 11/20. 0.0898 s / img. ETA=0:00:00
[05/30 17:38:24 d2.evaluation.evaluator]: Total inference time: 0:00:01.460618 (0.097375 s / img per device, on 1 devices)
[05/30 17:38:24 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:01 (0.085200 s / img per device, on 1 devices)
[05/30 17:38:24 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[05/30 17:38:24 d2.evaluation.coco_evaluation]: Saving results to ./output/coco_instances_results.json
[05/30 17:38:24 d2.evaluation.coco_evaluation]: Evaluating predictions ...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-70-6d95f2f04410> in <module>()
      3 evaluator = COCOEvaluator(mmfashion_instance_test, cfg, False, output_dir="./output/")
      4 val_loader = build_detection_test_loader(cfg, mmfashion_instance_test)
----> 5 inference_on_dataset(trainer.model, val_loader, evaluator)
      6 # another equivalent way is to use trainer.test

6 frames

/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py in evaluateImg(self, imgId, catId, aRng, maxDet)
    249 
    250         for g in gt:
--> 251             if g['ignore'] or (g['area']<aRng[0] or g['area']>aRng[1]):
    252                 g['_ignore'] = 1
    253             else:

KeyError: 'area'

```

and here is my cfg:

```
CUDNN_BENCHMARK: False
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: ()
  PROPOSAL_FILES_TRAIN: ()
  TEST: ()
  TRAIN: ('mmfashion-train',)
GLOBAL:
  HACK: 1.0
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.9, 0.9]
    TYPE: relative_range
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: choice
MODEL:
  ANCHOR_GENERATOR:
    ANGLES: [[-90, 0, 90]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES: [[32], [64], [128], [256], [512]]
  BACKBONE:
    FREEZE_AT: 2
    NAME: build_resnet_fpn_backbone
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    NORM: 
    OUT_CHANNELS: 256
  KEYPOINT_ON: False
  LOAD_PROPOSALS: False
  MASK_ON: False
  META_ARCHITECTURE: GeneralizedRCNN
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: False
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE: [False, False, False, False]
    DEPTH: 101
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.4, 0.5]
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS: ((10.0, 10.0, 5.0, 5.0), (20.0, 20.0, 10.0, 10.0), (30.0, 30.0, 15.0, 15.0))
    IOUS: (0.5, 0.6, 0.7)
  ROI_BOX_HEAD:
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    CLS_AGNOSTIC_BBOX_REG: False
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FastRCNNConvFCHead
    NORM: 
    NUM_CONV: 0
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    IOU_LABELS: [0, 1]
    IOU_THRESHOLDS: [0.5]
    NAME: StandardROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 50
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: True
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS: (512, 512, 512, 512, 512, 512, 512, 512)
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: True
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
    CONV_DIM: 256
    NAME: MaskRCNNConvUpsampleHead
    NORM: 
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    BOUNDARY_THRESH: -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5', 'p6']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.3, 0.7]
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 1000
    PRE_NMS_TOPK_TRAIN: 2000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    LOSS_WEIGHT: 1.0
    NAME: SemSegFPNHead
    NORM: GN
    NUM_CLASSES: 54
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_101_FPN_3x/137851257/model_final_f6e8b1.pkl
OUTPUT_DIR: ./output
SEED: -1
SOLVER:
  BASE_LR: 0.00025
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: False
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 300
  MOMENTUM: 0.9
  NESTEROV: False
  STEPS: (210000, 250000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: False
    FLIP: True
    MAX_SIZE: 4000
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 0
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
```
