### ISSUE TITLE
Potential bugs/missing features for customized anchor ratio&size 

### ISSUE THREAD

**Issue by XiaoSong9905** [facebookresearch/detectron2#1648]
When loading a full detection model weight (e.g.  
```yaml
WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
``` 
)  

and specify anchor size (e.g. 
```yaml
MODEL:
    ANCHOR_GENERATOR:
        SIZES: [[256], [512]] # default [[32], [64], [128], [256], [512]]  
    RPN:
        IN_FEATURES: ["p5", "p6"] # default ["p2", "p3", "p4", "p5", "p6"] 
```
in the configuration file). The model unable to load new customized anchor in this case.  This is because when `fvcore.common.checkpoint.Checkpointer._load_model()` is called, keys like `proposal_generator.anchor_generator.cell_anchors.0/1/2/3/4` (the old anchor size) are loaded into the model. 

I'm wondering if there's a way to add support to this?
