### ISSUE TITLE
Pre-Built Detectron2 For Windows

### ISSUE THREAD

**Issue by shlpu** [facebookresearch/detectron2#1712]
Are you willing to release Pre-Built Detectron2 For Windows? Thanks a lot.

**Comment by ppwwyyxx** [comment]
We don't have such plans, but would appreciate it if anyone is willing to help us set up the CI on windows.

**Comment by sarthakforwet** [comment]
Hey @shlpu nice thought! @ppwwyyxx I wanna work on this issue can you please tell me what I need to know related to the issue before start working on it. Thanks.

**Comment by ppwwyyxx** [comment]
We use CircleCI at https://github.com/facebookresearch/detectron2/blob/master/.circleci/config.yml. It provides windows support so it can be configured with automated scripts to install dependencies, build detectron2 and run tests for every commit, on windows. https://github.com/pytorch/vision/blob/master/.circleci/config.yml can be used as a reference.

**Comment by sarthakforwet** [comment]
@ppwwyyxx I am successful in installing dependencies with `windows executor` but quite unable to find out how should I install `detectron2` on windows.

Here's my sample config file (only for experiments not the complete ready code) - 
```
version: 2.1

windows-cpu: &windows_cpu
    machine:
      resource_class: windows.medium
      image: windows-server-2019-vs2019:stable
      shell: bash.exe

windows-gpu: &windows_gpu
    machine:
      resource_class: windows.gpu.nvidia.medium
      image: windows-server-2019-nvidia:stable
      shell: bash.exe

cpu: &cpu
  docker:
    - image: circleci/python:3.6.8-stretch
  resource_class: medium

gpu: &gpu
  machine:
    image: ubuntu-1604:201903-01
    docker_layer_caching: true
  resource_class: gpu.small

setup_venv: &setup_venv
  - run:
      name: Setup Virtual Env
      command: |
        python -m venv ~/venv
        echo ". ~/venv/bin/activate" >> $BASH_ENV
        . ~/venv/bin/activate
        python --version
        which python
        which pip
        pip install --upgrade pip

install_dep: &install_dep
  - run:
      name: Install Dependencies
      command: |
        python -m pip install --upgrade pip
        python --version
        python -m pip install 'git+https://github.com/facebookresearch/fvcore'
        python -m pip install opencv-python pytest-xdist
        pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

install_detectron2: &install_detectron2
  - run:
      name: Install Detectron2
      command: |
        git clone https://github.com/conansherry/detectron2
        cd detectron2
        python setup.py build develop

jobs:
  windows_cpu_tests:
    <<: *windows_cpu
    steps:
      - checkout
      - <<: *install_dep
      - <<: *install_detectron2


workflows:
  regular:
    jobs:
      - windows_cpu_tests
```

I am unable to build detectron2 this way. I've found a [windows build for detectron2](https://github.com/conansherry/detectron2#build-detectron2), can we build it like that or any other way? Thanks
