### ISSUE TITLE
config.py not utilized. 

### ISSUE THREAD

**Issue by Adblu** [facebookresearch/detectron2#1957]
I have defined my own parameters in file pointrend/point_rend/config.py
for example:
```
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.GAMMA = 0.05
```

However in the log file I'm getting:

```
SOLVER:
  BASE_LR: 0.002
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 200
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: False
    NORM_TYPE: 2.0
  GAMMA: 0.1

```

You can see that gamma and lr rate are different. Is config file used anyway ?
In which place shall i configure my own parameters ?
