### ISSUE TITLE
Learning rate 0 while trying to resume from a checkpoint

### ISSUE THREAD

**Issue by AlexCSTech** [facebookresearch/detectron2#2424]
## Problem Description
When I try to resume from a checkpoint, there is an error.
My model is Panoptic Deeplab
```
ERROR [12/27 18:20:50 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 135, in train
    self.after_step()
  File "/home/alex/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 165, in after_step
    h.after_step()
  File "/home/alex/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/engine/hooks.py", line 240, in after_step
    self._scheduler.step()
  File "/home/alex/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 154, in step
    values = self.get_lr()
  File "/home/alex/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/projects/deeplab/lr_scheduler.py", line 57, in get_lr
    for base_lr in self.base_lrs
  File "/home/alex/anaconda3/envs/pytorch/lib/python3.6/site-packages/detectron2/projects/deeplab/lr_scheduler.py", line 57, in <listcomp>
    for base_lr in self.base_lrs
ValueError: math domain error
```
Here is the config file:
```
_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "h48.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "d2_hrnet"
  RESNETS:
    NORM: "BN"
    DEPTH: 48
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  SEM_SEG_HEAD:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    PROJECT_FEATURES: ["res2", "res3", "res4"]
    PROJECT_CHANNELS: [32, 64, 128]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [3, 6, 9]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 256
    CONVS_DIM: 256
    COMMON_STRIDE: 4
    NUM_CLASSES: 19
    LOSS_TYPE: "hard_pixel_mining"
    NORM: "BN"
  INS_EMBED_HEAD:
    NAME: "PanopticDeepLabInsEmbedHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    PROJECT_FEATURES: ["res2", "res3", "res4"]
    PROJECT_CHANNELS: [32, 64, 128]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [3, 6, 9]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 32
    CONVS_DIM: 128
    COMMON_STRIDE: 4
    NORM: "BN"
    CENTER_LOSS_WEIGHT: 200.0
    OFFSET_LOSS_WEIGHT: 0.01
SOLVER:
  MAX_ITER: 90000
  IMS_PER_BATCH: 1
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (512, 1024)
```
Here is the base config:
```
MODEL:
  META_ARCHITECTURE: "PanopticDeepLab"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res5"]
    RES5_DILATION: 2
  SEM_SEG_HEAD:
    NAME: "PanopticDeepLabSemSegHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 256
    CONVS_DIM: 256
    COMMON_STRIDE: 4
    NUM_CLASSES: 19
    LOSS_TYPE: "hard_pixel_mining"
    NORM: "SyncBN"
  INS_EMBED_HEAD:
    NAME: "PanopticDeepLabInsEmbedHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 32
    CONVS_DIM: 128
    COMMON_STRIDE: 4
    NORM: "SyncBN"
    CENTER_LOSS_WEIGHT: 200.0
    OFFSET_LOSS_WEIGHT: 0.01
  PANOPTIC_DEEPLAB:
    STUFF_AREA: 2048
    CENTER_THRESHOLD: 0.1
    NMS_KERNEL: 7
    TOP_K_INSTANCE: 200
DATASETS:
  TRAIN: ("cityscapes_fine_panoptic_train",)
  TEST: ("cityscapes_fine_panoptic_val",)
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 60000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 32
INPUT:
  MIN_SIZE_TRAIN: (512, 640, 704, 832, 896, 1024, 1152, 1216, 1344, 1408, 1536, 1664, 1728, 1856, 1920, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (1024, 2048)
DATALOADER:
  NUM_WORKERS: 10
VERSION: 2
```

I'm trying to train on single GPU so I changed NORM from syncBN to BN and changed IMS_PER_BATCH from 32 to 1.
I can train the model normally but cannot resume checkpoint.
