### ISSUE TITLE
[torchscript deployment] Support Keypoint R-CNN in tracing

### ISSUE THREAD

**Issue by cognitiveRobot** [facebookresearch/detectron2#2612]
### Instructions To Reproduce the Issue:

1. Build and launch container
```
cd docker/
# Build:
docker build --build-arg USER_ID=$UID -t detectron2:v0 .

docker build -t detectron2-deploy:v0 -f deploy.Dockerfile .

# Launch:
docker run --gpus all -it detectron2-deploy:v0
```
2. Install onnx
```
pip install onnx
```

### Full runnable code or full changes:
https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/export_model.py#L73
@def export_tracing(torch_model, inputs):
`assert TORCH_VERSION >= (1, 8)` to `assert TORCH_VERSION >= (1, 7)`

### my_config
```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True #True
  RESNETS:
    DEPTH: 50

  KEYPOINT_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5  # Keypoint AP degrades (though box AP improves) when using plain L1 loss
  RPN:
    # Detectron1 uses 2000 proposals per-batch, but this option is per-image in detectron2.
    # 1000 proposals per-image is found to hurt box AP.
    # Therefore we increase it to 1500 per-image.
    POST_NMS_TOPK_TRAIN: 1500

  ROI_KEYPOINT_HEAD:
    #CONV_DIMS: (512, 512, 512, 512, 512, 512, 512, 512)
    #CONV_DIMS: (512, 512)
    NUM_KEYPOINTS: 1
    LOSS_WEIGHT: 0.05

SOLVER:
  STEPS: (2100, 2500) #(84000, 100000) #
  MAX_ITER: 2700 #108000 #
  WARMUP_ITERS: 1000
  BASE_LR: 0.002

DATASETS:
  TRAIN: ("fruit_train",)  
  TEST: ("fruit_val",) 

INPUT:
  MIN_SIZE_TRAIN: (768,)
  MAX_SIZE_TRAIN: 768

  MIN_SIZE_TEST: 0
  MAX_SIZE_TEST: 4112
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: [768, 768]

TEST:
  DETECTIONS_PER_IMAGE: 2000
  KEYPOINT_OKS_SIGMAS: [0.025]
```

### Exact command:
```
# this example also tries GPU instead of CPU
./export_model.py --config-file <my_config_file_as_above> \
    --output ./output --export-method tracing --format torchscript \
    MODEL.WEIGHTS <my_model_file.pth> \
    MODEL.DEVICE cuda
```
convertion is successful. But when I run the following command.

```
./build/torchscript_traced_mask_rcnn output/model.ts input.jpg tracing
```
I get the following `runtime error`

### __Full logs__ or other relevant observations:
```
appuser@8d2e889a36ba:~/detectron2_repo/tools/deploy$ ./build/torchscript_traced_mask_rcnn output/model.ts /tmp/inputs/gold.jpg tracing
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 30, in forward
    _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, = (_2).forward(x0, )
    _26 = (_1).forward(_14, _15, _16, _17, _18, _19, _20, _21, _22, image_size, )
    _27 = (_0).forward(_14, _26, _15, _16, _23, image_size, _24, _25, )
           ~~~~~~~~~~~ <--- HERE
    _28, _29, _30, _31, _32, _33, = _27
    return (_28, _29, _30, _31, _32, _33)
  File "code/__torch__/detectron2/modeling/roi_heads/roi_heads.py", line 149, in forward
    _88 = (_3).forward(_87, tensor2, )
    _89 = (_2).forward(argument_1, tensor2, argument_3, argument_4, argument_8, )
    _90, _91, = (_1).forward(_89, tensor2, )
                 ~~~~~~~~~~~ <--- HERE
    return (tensor2, _83, _86, _88, _90, _91)
  File "code/__torch__/detectron2/modeling/roi_heads/keypoint_head.py", line 5458, in forward
    _3651 = torch.to(_3650, dtype=4, layout=0, device=torch.device("cuda:0"), pin_memory=None, non_blocking=False, copy=False, memory_format=None)
    _3652 = annotate(List[Optional[Tensor]], [None, None, _3651])
    _3653 = torch.split_with_sizes(torch.index(_3649, _3652), [84], 0)
            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _3654, = _3653
    _3655 = _3654

Traceback of TorchScript, original code (most recent call last):
/home/appuser/.local/lib/python3.6/site-packages/torch/tensor.py(476): split
/home/appuser/detectron2_repo/detectron2/modeling/roi_heads/keypoint_head.py(123): keypoint_rcnn_inference
/home/appuser/detectron2_repo/detectron2/modeling/roi_heads/keypoint_head.py(204): forward
/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(709): _slow_forward
/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(725): _call_impl
/home/appuser/detectron2_repo/detectron2/modeling/roi_heads/roi_heads.py(868): _forward_keypoint
/home/appuser/detectron2_repo/detectron2/modeling/roi_heads/roi_heads.py(768): forward_with_given_boxes
/home/appuser/detectron2_repo/detectron2/modeling/roi_heads/roi_heads.py(741): forward
/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(709): _slow_forward
/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(725): _call_impl
/home/appuser/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py(212): inference
./export_model.py(109): forward
/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(709): _slow_forward
/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(725): _call_impl
/home/appuser/.local/lib/python3.6/site-packages/torch/jit/_trace.py(940): trace_module
/home/appuser/.local/lib/python3.6/site-packages/torch/jit/_trace.py(742): trace
./export_model.py(121): export_tracing
./export_model.py(183): <module>
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 95 (input tensor's size at dimension 0), but got split_sizes=[84]

Aborted (core dumped)
```

## Expected behavior:

I was expecting to run `torchscript_traced_mask_rcnn` successfully.

## Environment:

```
Failed to load OpenCL runtime
----------------------  -------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.19.5
detectron2              0.3 @/home/appuser/detectron2_repo/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   3.5, 3.7, 5.0, 5.2, 5.3, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1+cu101 @/home/appuser/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda
TORCH_CUDA_ARCH_LIST    Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing
Pillow                  8.1.0
torchvision             0.8.2+cu101 @/home/appuser/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.3
cv2                     3.2.0
----------------------  -------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

What am I missing here? Can you please help to fix the issue?
Thanks in advance.
