### ISSUE TITLE
[PointRend] Problem with traced on CPU model

### ISSUE THREAD

**Issue by QNester** [facebookresearch/detectron2#3492]
Hi!

## My purpose
I want to fetch dynamic size masks after tracing PointRend model. I want use this model in production, but I have only CPU-instances to deployment. 

I have no this issue with tracing on CUDA. All works fine on CUDA and I have dynamic sized masks. I have this issue only after tracing on CPU. 

## Instructions To Reproduce the Issue:
1. Train PointRend model with own dataset
2. Exporting model with torch jit trace using [this script](https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py). In [this line](https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py#L117) I changed flag `do_postprocess` to `True`. My
3. Load jit model and run prediction
4. Get error `RuntimeError: shape '[699, 540]' is invalid for input of size 174150`

## My code
1. ConfigFile
```
# config
CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 1
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
    - test
  TRAIN:
    - train
GLOBAL:
  HACK: 1.0
INPUT:
  COLOR_AUG_SSD: false
  CROP:
    ENABLED: false
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE:
    - 0.9
    - 0.9
    TYPE: relative_range
  FORMAT: BGR
  MASK_FORMAT: bitmask
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN:
  - 640
  - 672
  - 704
  - 736
  - 768
  - 800
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
    - - 64
    - - 128
    - - 256
    - - 512
  BACKBONE:
    FREEZE_AT: 2
    NAME: build_resnet_fpn_backbone
  DEVICE: cpu
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    NORM: ''
    OUT_CHANNELS: 256
  IMPLICIT_POINTREND:
    IMAGE_FEATURE_ENABLED: true
    PARAMS_L2_REGULARIZER: 1.0e-05
    POS_ENC_ENABLED: true
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN:
  - 103.53
  - 116.28
  - 123.675
  PIXEL_STD:
  - 57.375
  - 57.12
  - 58.395
  POINT_HEAD:
    CLS_AGNOSTIC_MASK: false
    COARSE_PRED_EACH_LAYER: true
    COARSE_SEM_SEG_HEAD_NAME: SemSegFPNHead
    FC_DIM: 256
    IMPORTANCE_SAMPLE_RATIO: 0.75
    IN_FEATURES:
    - p2
    NAME: StandardPointHead
    NUM_CLASSES: 22
    NUM_FC: 3
    OVERSAMPLE_RATIO: 3
    SUBDIVISION_NUM_POINTS: 784
    SUBDIVISION_STEPS: 5
    TRAIN_NUM_POINTS: 196
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 101
    NORM: FrozenBN
    NUM_GROUPS: 32
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: false
    WIDTH_PER_GROUP: 8
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS: &id001
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NORM: ''
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    CLS_AGNOSTIC_BBOX_REG: false
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FastRCNNConvFCHead
    NORM: ''
    NUM_CONV: 0
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: true
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    IOU_LABELS:
    - 0
    - 1
    IOU_THRESHOLDS:
    - 0.5
    NAME: StandardROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 22
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: true
    SCORE_THRESH_TEST: 0.3
  ROI_KEYPOINT_HEAD:
    CONV_DIMS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: false
    CONV_DIM: 256
    FC_DIM: 1024
    IN_FEATURES:
    - p2
    NAME: PointRendMaskHead
    NORM: ''
    NUM_CONV: 4
    NUM_FC: 2
    OUTPUT_SIDE_RESOLUTION: 7
    POINT_HEAD_ON: true
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ''
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: *id001
    BOUNDARY_THRESH: -1
    CONV_DIMS:
    - -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    - p6
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 1000
    PRE_NMS_TOPK_TRAIN: 2000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    LOSS_WEIGHT: 1.0
    NAME: SemSegFPNHead
    NORM: GN
    NUM_CLASSES: 54
  WEIGHTS: PycharmProjects/PointRendTrainer/output_1/model_0029999.pth
OUTPUT_DIR: PycharmProjects/PointRendTrainer/output_1
SEED: -1
SOLVER:
  AMP:
    ENABLED: false
  BASE_LR: 0.00025
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: false
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 50000
  MOMENTUM: 0.9
  NESTEROV: false
  REFERENCE_WORLD_SIZE: 0
  STEPS: []
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES:
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 2000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
```
2. Command for tracing model: 
```
python trace_model.py --config-file PycharmProjects/PointRendTrainer/predict/config_model_predict.yaml --output ./traced_model --export-method tracing --format torchscript
```

3. My predictor script
```
import torch
from PIL import Image
import numpy as np
import torchvision

model = torch.jit.load('PycharmProjects/PointRendTrainer/train/traced_model/model.ts')
image = Image.open('PycharmProjects/PointRendTrainer/examples/3.jpg').convert('RGB')
np_image = np.asarray(image)
image_tensor = torch.as_tensor(np_image.astype("float32").transpose(2, 0, 1))

print(model.code)
pred = model(image_tensor)
print(pred)
```

4. Command to run predictor script:
```
python ./predictor.py
```

5. Logs
```
def forward(self,
    argument_1: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor]:
  _0 = self.model.roi_heads
  _1 = self.model.proposal_generator
  _2 = self.model.backbone
  _3 = self.model.pixel_std
  _4 = self.model.pixel_mean
  x = torch.to(argument_1, dtype=0, layout=0, device=torch.device("cpu"))
  t = torch.div(torch.sub(x, _4), _3)
  _5 = ops.prim.NumToTensor(torch.size(t, 1))
  _6 = ops.prim.NumToTensor(torch.size(t, 2))
  image_size = torch.stack([_5, _6])
  max_size, _7 = torch.max(torch.stack([image_size]), 0)
  _8 = torch.floor_divide(torch.add(max_size, CONSTANTS.c0), CONSTANTS.c1)
  max_size0 = torch.mul(_8, CONSTANTS.c1)
  _9 = torch.sub(torch.select(max_size0, 0, -1), torch.select(image_size, 0, 1))
  _10 = int(_9)
  _11 = torch.sub(torch.select(max_size0, 0, -2), torch.select(image_size, 0, 0))
  _12 = torch.constant_pad_nd(t, [0, _10, 0, int(_11)], 0.)
  batched_imgs = torch.unsqueeze_(_12, 0)
  x0 = torch.contiguous(batched_imgs)
  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, = (_2).forward(x0, )
  _23 = (_1).forward(_13, _14, _15, _16, _17, _18, _19, _20, _21, image_size, )
  _24 = (_0).forward(_13, _23, _14, _15, _22, image_size, )
  _25, _26, _27, _28, = _24
  output_height = torch.select(image_size, 0, 0)
  _29 = annotate(number, output_height)
  _30 = annotate(number, output_height)
  _31 = int(output_height)
  output_width = torch.select(image_size, 0, 1)
  _32 = annotate(number, output_width)
  _33 = annotate(number, output_width)
  _34 = int(output_width)
  output_width_tmp = torch.to(output_width, 6)
  output_height_tmp = torch.to(output_height, 6)
  _35 = torch.stack([output_height, output_width])
  scale_x = torch.div(output_width_tmp, torch.select(image_size, 0, 1))
  scale_y = torch.div(output_height_tmp, torch.select(image_size, 0, 0))
  _36 = torch.slice(_25, 0, 0, 9223372036854775807)
  _37 = torch.slice(_36, 1, 0, 9223372036854775807, 2)
  _38 = torch.mul_(_37, scale_x)
  _39 = torch.slice(_25, 0, 0, 9223372036854775807)
  _40 = torch.slice(_39, 1, 0, 9223372036854775807, 2)
  _41 = torch.copy_(_40, _38)
  _42 = torch.slice(_25, 0, 0, 9223372036854775807)
  _43 = torch.slice(_42, 1, 1, 9223372036854775807, 2)
  _44 = torch.mul_(_43, scale_y)
  _45 = torch.slice(_25, 0, 0, 9223372036854775807)
  _46 = torch.slice(_45, 1, 1, 9223372036854775807, 2)
  _47 = torch.copy_(_46, _44)
  h, w, = torch.unbind(_35)
  _48 = annotate(number, h)
  _49 = annotate(number, w)
  _50 = annotate(number, h)
  _51 = annotate(number, w)
  _52 = torch.slice(_25, 0, 0, 9223372036854775807)
  x1 = torch.clamp(torch.select(_52, 1, 0), 0, _51)
  _53 = torch.slice(_25, 0, 0, 9223372036854775807)
  y1 = torch.clamp(torch.select(_53, 1, 1), 0, _50)
  _54 = torch.slice(_25, 0, 0, 9223372036854775807)
  x2 = torch.clamp(torch.select(_54, 1, 2), 0, _49)
  _55 = torch.slice(_25, 0, 0, 9223372036854775807)
  y2 = torch.clamp(torch.select(_55, 1, 3), 0, _48)
  box = torch.stack([x1, y1, x2, y2], -1)
  _56 = torch.slice(box, 0, 0, 9223372036854775807)
  _57 = torch.select(_56, 1, 2)
  _58 = torch.slice(box, 0, 0, 9223372036854775807)
  widths = torch.sub(_57, torch.select(_58, 1, 0))
  _59 = torch.slice(box, 0, 0, 9223372036854775807)
  _60 = torch.select(_59, 1, 3)
  _61 = torch.slice(box, 0, 0, 9223372036854775807)
  heights = torch.sub(_60, torch.select(_61, 1, 1))
  item = torch.__and__(torch.gt(widths, 0.), torch.gt(heights, 0.))
  item0 = torch.to(item, dtype=11, layout=0, device=torch.device("cpu"))
  _62 = annotate(List[Optional[Tensor]], [item0])
  tensor = torch.index(box, _62)
  tensor0 = torch.to(tensor, torch.device("cpu"), 6)
  item1 = torch.to(item0, dtype=11, layout=0, device=torch.device("cpu"))
  _63 = annotate(List[Optional[Tensor]], [item1])
  _64 = torch.index(_26, _63)
  item2 = torch.to(item1, dtype=11, layout=0, device=torch.device("cpu"))
  _65 = annotate(List[Optional[Tensor]], [item2])
  _66 = torch.index(_27, _65)
  item3 = torch.to(item2, dtype=11, layout=0, device=torch.device("cpu"))
  _67 = annotate(List[Optional[Tensor]], [item3])
  _68 = torch.slice(torch.index(_28, _67), 0, 0, 9223372036854775807)
  _69 = torch.slice(torch.select(_68, 1, 0), 1, 0, 9223372036854775807)
  masks = torch.slice(_69, 2, 0, 9223372036854775807)
  _70 = torch.arange(2, dtype=None, layout=0, device=torch.device("cpu"), pin_memory=False)
  inds, inds0, = torch.chunk(_70, 2)
  img_masks = torch.zeros([2, _31, _34], dtype=11, layout=None, device=torch.device("cpu"), pin_memory=False)
  _71 = torch.slice(torch.unsqueeze(masks, 1), 2, 0, 9223372036854775807)
  _72 = torch.slice(_71, 3, 0, 9223372036854775807)
  inds1 = torch.to(inds, dtype=4, layout=0, device=torch.device("cpu"))
  _73 = annotate(List[Optional[Tensor]], [inds1])
  masks0 = torch.index(_72, _73)
  inds2 = torch.to(inds1, dtype=4, layout=0, device=torch.device("cpu"))
  _74 = annotate(List[Optional[Tensor]], [inds2])
  boxes = torch.index(tensor0, _74)
  _75, _76 = torch.min(boxes, 0)
  _77 = torch.slice(torch.floor(_75), 0, 0, 2)
  _78 = torch.clamp(torch.sub(_77, CONSTANTS.c2), 0)
  x0_int, y0_int, = torch.unbind(torch.to(_78, 3))
  _79 = int(x0_int)
  _80 = int(y0_int)
  _81 = annotate(number, x0_int)
  _82 = annotate(number, y0_int)
  _83 = torch.slice(boxes, 0, 0, 9223372036854775807)
  _84 = torch.ceil(torch.max(torch.select(_83, 1, 2)))
  _85 = torch.clamp(torch.add(_84, CONSTANTS.c2), None, _33)
  x1_int = torch.to(_85, 3)
  _86 = int(x1_int)
  _87 = annotate(number, x1_int)
  _88 = torch.slice(boxes, 0, 0, 9223372036854775807)
  _89 = torch.ceil(torch.max(torch.select(_88, 1, 3)))
  _90 = torch.clamp(torch.add(_89, CONSTANTS.c2), None, _30)
  y1_int = torch.to(_90, 3)
  _91 = int(y1_int)
  _92 = annotate(number, y1_int)
  x00, y0, x10, y10, = torch.split(boxes, 1, 1)
  N = ops.prim.NumToTensor(torch.size(masks0, 0))
  _93 = int(N)
  _94 = int(N)
  _95 = torch.arange(_82, _92, 1, dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
  img_y = torch.add(_95, CONSTANTS.c3)
  _96 = torch.arange(_81, _87, 1, dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
  img_x = torch.add(_96, CONSTANTS.c3)
  _97 = torch.div(torch.sub(img_y, y0), torch.sub(y10, y0))
  img_y0 = torch.sub(torch.mul(_97, CONSTANTS.c4), CONSTANTS.c2)
  _98 = torch.div(torch.sub(img_x, x00), torch.sub(x10, x00))
  img_x0 = torch.sub(torch.mul(_98, CONSTANTS.c4), CONSTANTS.c2)
  _99 = torch.slice(img_x0, 0, 0, 9223372036854775807)
  _100 = torch.slice(torch.unsqueeze(_99, 1), 2, 0, 9223372036854775807)
  _101 = ops.prim.NumToTensor(torch.size(img_y0, 1))
  _102 = int(_101)
  _103 = ops.prim.NumToTensor(torch.size(img_x0, 1))
  gx = torch.expand(_100, [_94, _102, int(_103)])
  _104 = torch.slice(img_y0, 0, 0, 9223372036854775807)
  _105 = torch.slice(_104, 1, 0, 9223372036854775807)
  _106 = torch.unsqueeze(_105, 2)
  _107 = ops.prim.NumToTensor(torch.size(img_y0, 1))
  _108 = int(_107)
  _109 = ops.prim.NumToTensor(torch.size(img_x0, 1))
  gy = torch.expand(_106, [_93, _108, int(_109)])
  grid = torch.stack([gx, gy], 3)
  grid0 = torch.to(grid, 6)
  img_masks0 = torch.grid_sampler(masks0, grid0, 0, 0, False)
  _110 = torch.slice(img_masks0, 0, 0, 9223372036854775807)
  masks_chunk = torch.select(_110, 1, 0)
  masks_chunk0 = torch.to(torch.ge(masks_chunk, 0.5), 11)
  _111 = torch.slice(torch.slice(img_masks, 1, _80, _91), 2, _79, _86)
  _112 = torch.view(masks_chunk0, [699, 540])
  inds3 = torch.to(inds2, dtype=4, layout=0, device=torch.device("cpu"))
  _113 = annotate(List[Optional[Tensor]], [inds3])
  _114 = torch.index_put_(_111, _113, _112)
  _115 = torch.slice(torch.unsqueeze(masks, 1), 2, 0, 9223372036854775807)
  _116 = torch.slice(_115, 3, 0, 9223372036854775807)
  inds4 = torch.to(inds0, dtype=4, layout=0, device=torch.device("cpu"))
  _117 = annotate(List[Optional[Tensor]], [inds4])
  masks1 = torch.index(_116, _117)
  inds5 = torch.to(inds4, dtype=4, layout=0, device=torch.device("cpu"))
  _118 = annotate(List[Optional[Tensor]], [inds5])
  boxes0 = torch.index(tensor0, _118)
  _119, _120 = torch.min(boxes0, 0)
  _121 = torch.slice(torch.floor(_119), 0, 0, 2)
  _122 = torch.clamp(torch.sub(_121, CONSTANTS.c2), 0)
  x0_int0, y0_int0, = torch.unbind(torch.to(_122, 3))
  _123 = int(x0_int0)
  _124 = int(y0_int0)
  _125 = annotate(number, x0_int0)
  _126 = annotate(number, y0_int0)
  _127 = torch.slice(boxes0, 0, 0, 9223372036854775807)
  _128 = torch.ceil(torch.max(torch.select(_127, 1, 2)))
  _129 = torch.clamp(torch.add(_128, CONSTANTS.c2), None, _32)
  x1_int0 = torch.to(_129, 3)
  _130 = int(x1_int0)
  _131 = annotate(number, x1_int0)
  _132 = torch.slice(boxes0, 0, 0, 9223372036854775807)
  _133 = torch.ceil(torch.max(torch.select(_132, 1, 3)))
  _134 = torch.clamp(torch.add(_133, CONSTANTS.c2), None, _29)
  y1_int0 = torch.to(_134, 3)
  _135 = int(y1_int0)
  _136 = annotate(number, y1_int0)
  x01, y00, x11, y11, = torch.split(boxes0, 1, 1)
  N0 = ops.prim.NumToTensor(torch.size(masks1, 0))
  _137 = int(N0)
  _138 = int(N0)
  _139 = torch.arange(_126, _136, 1, dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
  img_y1 = torch.add(_139, CONSTANTS.c3)
  _140 = torch.arange(_125, _131, 1, dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
  img_x1 = torch.add(_140, CONSTANTS.c3)
  _141 = torch.div(torch.sub(img_y1, y00), torch.sub(y11, y00))
  img_y2 = torch.sub(torch.mul(_141, CONSTANTS.c4), CONSTANTS.c2)
  _142 = torch.div(torch.sub(img_x1, x01), torch.sub(x11, x01))
  img_x2 = torch.sub(torch.mul(_142, CONSTANTS.c4), CONSTANTS.c2)
  _143 = torch.slice(img_x2, 0, 0, 9223372036854775807)
  _144 = torch.slice(torch.unsqueeze(_143, 1), 2, 0, 9223372036854775807)
  _145 = ops.prim.NumToTensor(torch.size(img_y2, 1))
  _146 = int(_145)
  _147 = ops.prim.NumToTensor(torch.size(img_x2, 1))
  gx0 = torch.expand(_144, [_138, _146, int(_147)])
  _148 = torch.slice(img_y2, 0, 0, 9223372036854775807)
  _149 = torch.slice(_148, 1, 0, 9223372036854775807)
  _150 = torch.unsqueeze(_149, 2)
  _151 = ops.prim.NumToTensor(torch.size(img_y2, 1))
  _152 = int(_151)
  _153 = ops.prim.NumToTensor(torch.size(img_x2, 1))
  gy0 = torch.expand(_150, [_137, _152, int(_153)])
  grid1 = torch.stack([gx0, gy0], 3)
  grid2 = torch.to(grid1, 6)
  img_masks1 = torch.grid_sampler(masks1, grid2, 0, 0, False)
  _154 = torch.slice(img_masks1, 0, 0, 9223372036854775807)
  masks_chunk1 = torch.select(_154, 1, 0)
  masks_chunk2 = torch.to(torch.ge(masks_chunk1, 0.5), 11)
  _155 = torch.slice(torch.slice(img_masks, 1, _124, _135), 2, _123, _130)
  _156 = torch.view(masks_chunk2, [700, 539])
  inds6 = torch.to(inds5, dtype=4, layout=0, device=torch.device("cpu"))
  _157 = annotate(List[Optional[Tensor]], [inds6])
  _158 = torch.index_put_(_155, _157, _156)
  tensor1 = torch.to(img_masks, torch.device("cpu"), 11)
  return (tensor0, _66, tensor1, _64, _35)

PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/nn/modules/module.py:1051: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return forward_call(*input, **kwargs)
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/nn/modules/module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return forward_call(*input, **kwargs)
Traceback (most recent call last):
  File "new_predictor.py", line 55, in <module>
    pred = model(image_tensor)
  File "PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/detectron2/export/flatten.py", line 158, in forward
    masks_chunk0 = torch.to(torch.ge(masks_chunk, 0.5), 11)
    _111 = torch.slice(torch.slice(img_masks, 1, _80, _91), 2, _79, _86)
    _112 = torch.view(masks_chunk0, [699, 540])
           ~~~~~~~~~~ <--- HERE
    inds3 = torch.to(inds2, dtype=4, layout=0, device=torch.device("cpu"))
    _113 = annotate(List[Optional[Tensor]], [inds3])

Traceback of TorchScript, original code (most recent call last):
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/layers/mask_ops.py(148): paste_masks_in_image
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/utils/memory.py(82): wrapped
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/structures/masks.py(525): to_bitmasks
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/modeling/postprocessing.py(69): detector_postprocess
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py(241): _postprocess
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py(216): inference
trace_model.py(122): inference
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/export/flatten.py(293): forward
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/nn/modules/module.py(1039): _slow_forward
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/nn/modules/module.py(1051): _call_impl
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/jit/_trace.py(959): trace_module
PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch/jit/_trace.py(744): trace
trace_model.py(131): export_tracing
trace_model.py(232): <module>
RuntimeError: shape '[699, 540]' is invalid for input of size 174150
```

## Expected behavior:
Predict works fine without errors: returns masks, boxes etc. **I want to attract your attention: this flow works fine when I change `DEVICE` to `cuda` and I have problem only with CPU.**

## Environment:

```
sys.platform            linux
Python                  3.7.11 (default, Jun 29 2021, 16:09:17) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
numpy                   1.21.2
detectron2              0.5 @/home/coddy/PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   /home/coddy/PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu111 @/home/coddy/PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce GTX 1060 6GB (arch=6.1)
CUDA_HOME               None - invalid!
Pillow                  8.3.2
torchvision             0.10.0+cu111 @/home/coddy/PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torchvision
torchvision arch flags  /home/coddy/PycharmProjects/PointRendTrainer/venv/lib64/python3.7/site-packages/torchvision/_C.so
fvcore                  0.1.5.post20210825
iopath                  0.1.8
cv2                     4.5.3
----------------------  -----------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```
