### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by an99990** [facebookresearch/detectron2#4028]
1. Full runnable code or full changes you made:
i am currently having out of memory issue running blendmask model while running the zed camera.
I would like to know how can I reduce the input shape of the model to not get out of memory.

this is the yaml file.
```

_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
SOLVER:
  STEPS: (280000, 360000)
  MAX_ITER: 400000
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "output/blendmask/R_101_dcni3_5x"
```
```

cfg = setup_cfg(args)
demo = VisualizationDemo(cfg)
root_dir = Path(__file__).parents[1]
path = root_dir / settings.paths[0].image
logger.info(f"image: {path}")
img = read_image(path, format="BGR")
predictions, vis  = demo.run_on_image(img)
```

```
2. What exact command you run:

4. __Full logs__ or other relevant observations:

`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 3.82 GiB total capacity; 228.58 MiB already allocated; 57.00 MiB free; 232.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

5. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:
get image with segmentation

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/main/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues
