### ISSUE TITLE
visualize_data.py dataloader can't stop

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#486]
1. what changes you made (`git diff`) or what code you wrote
```
Nothing
```
2. what exact command you run:
```
python visualize_data.py \
  --config-file configs/COCO-Detection/visual_gt.yaml \ 
  --source dataloader \
  --output vis_gt
```
and the `visual_gt.yaml` is:
```
_BASE_: "../Base-RCNN-C4.yaml"                            
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_val",)
```

3. what you observed (including the full logs):

The program will not stop after a full epoch. I.e, it will load data over and over again.
