### ISSUE TITLE
Can't change Pointrend Input Layer 

### ISSUE THREAD

**Issue by Yousefshukry** [facebookresearch/detectron2#5134]
Hello, 

I'm trying to modify Pointrend project to do the following: 
Instead of using 3 channel RGB input for training, I'll increase the number of channels to 4 and include the depth dimension.

In order to do that, I created my own build_train_loader and DatasetMapper (build_custom_train_loader) to load my data correctly given depth files. I also made sure input images and depth are of the same size. 

My data loader now returns (4, 1333, 1920) dimension images. 

Now I'm getting an expected error: 

`Pytorch RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0`

What I'm trying to do is change the input layer dimensions to 4 instead of 3, then modify the pretrained weights by loading them into a Dict and adding a 4th dimension that is the average of RGB channels and train accordingly. 

I tried the following to change the input layer from (3) to (4) dimension:

I tried modifying the Base-RCNN-FPN.yaml file to add INPUT.NUM_CHANNELS = 4 as follows:
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: "RGB"  # Image format (typically "RGB")
  NUM_CHANNELS: 4  # Change this to 4
  HEIGHT: 1333  # Input image height
  WIDTH: 1920   # Input image width
VERSION: 2
```

I also tried modifying the setup function where I changed:
cfg.MODEL.RESNETS.STEM_OUT_CHANNELS
cfg.MODEL.FPN.IN_FEATURES = 4

I also played around with cfg.MODEL.RESNETS.OUT_FEATURES
```
def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    
    #import pdb; pdb.set_trace()
    add_pointrend_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)

    # Update this line if we want to resume training from a previous checkpoints file
    # cfg.MODEL.WEIGHTS = "checkpoints/active_train/model_0000099.pth"


    cfg.MODEL.DEVICE = "cuda"
    cfg.DATALOADER.NUM_WORKERS = 1
    cfg.SOLVER.CHECKPOINT_PERIOD = 500

    # number of classes
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2
    cfg.MODEL.POINT_HEAD.NUM_CLASSES = 2

    # Change number of channels
    # cfg.INPUT.NUM_CHANNELS = 4
    input_channels = 4  
    cfg.MODEL.RESNETS.STEM_OUT_CHANNELS = input_channels * 2  # Default is 3 * 2 = 6  
    # cfg.MODEL.INPUT.NUM_CHANNELS = 4
    cfg.MODEL.FPN.IN_FEATURES = 4
    cfg.MODEL.RESNETS.OUT_FEATURES = ['res2', 'res3', 'res4', 'res5', 'res6']
    cfg.MODEL.ROI_HEADS.OUT_FEATURES = ['p2', 'p3', 'p4', 'p5', 'p6']
    cfg.MODEL.SEM_SEG_HEAD.IN_FEATURES = ['p2', 'p3', 'p4', 'p5', 'p6']
    
    # not flipping
    if args.dataset in ['epick_hos']:
        cfg.INPUT.RANDOM_FLIP = "none"
        

    cfg.freeze()
    default_setup(cfg, args)
    return cfg
```

Nothing seems to be working with me, Am I missing something? 
What exactly do I need to do in order to modify the input layer dimensions to be (4) and allow me to train the modeling using an extra signal? 

Thank you.
