### ISSUE TITLE
Using own trained model

### ISSUE THREAD

**Issue by enjoykcc456** [facebookresearch/detectron2#647]
Hello,
I have trained a detectron model using other training software which also output a .yaml and .pkl to me. However when i try to make inference using them, error occurs. May i know what should i do to so that i can make inference with it using detectron2? I am new to this, kindly let me know if there is anything i can do to fix it. Million thanks in advance.

This is the error when i run `cfg.merge_from_file('deploy_file/R50FPN.yaml')` in the script:

> Traceback (most recent call last):
>   File "grab_infer.py", line 20, in <module>
>     cfg.merge_from_file('deploy_file/R50FPN.yaml')
>   File "/home/appuser/detectron2_repo/detectron2/config/config.py", line 45, in merge_from_file
>     self.merge_from_other_cfg(loaded_cfg)
>   File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/common/config.py", line 121, in merge_from_other_cfg
>     return super().merge_from_other_cfg(cfg_other)
>   File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg    _merge_a_into_b(cfg_other, self, self, [])
>   File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
>     raise KeyError("Non-existent config key: {}".format(full_key))
> KeyError: 'Non-existent config key: FAST_RCNN'

This is the content inside the 'R50FPN.yaml':
```
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  FPN_ON: true
  MULTILEVEL_ROIS: true
  MULTILEVEL_RPN: true
MODEL:
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  FASTER_RCNN: true
  MASK_ON: true
  NUM_CLASSES: 2
  TYPE: generalized_rcnn
MRCNN:
  CONV_INIT: MSRAFill
  DILATION: 1
  RESOLUTION: 28
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
NUM_GPUS: 1
OUTPUT_DIR: /opt/tmp
SOLVER:
  BASE_LR: 0.001
  GAMMA: 0.1
  LR_POLICY: steps_with_decay
  MAX_ITER: 8000
  STEPS:
  - 0
  - 5600
  - 7200
  WEIGHT_DECAY: 0.0005
TEST:
  DATASETS: ('coco_cod_val',)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 1000
  RPN_PRE_NMS_TOP_N: 1000
  SCALE: '800'
TRAIN:
  BATCH_SIZE_PER_IM: 256
  DATASETS: ('coco_cod_train',)
  MAX_SIZE: 1333
  RPN_PRE_NMS_TOP_N: 2000
  SCALES: (800,)
  WEIGHTS: /opt/DNN/dnn_impl/cod_detectron/configs/R-50.pkl
```
I realised the format is different compared to what in config directory. Is there anything i can do to make this model works? Thank you.
